version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      DB_USERNAME: root
      DB_PASSWORD: 123456
      DB_NAME: app_development
      DB_PORT: 3306
      DB_HOST: db
      RAILS_ENV: development
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    depends_on:
      - db
