default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 123456
  host: 127.0.0.1

development:
  <<: *default
  database: app_development

test:
  <<: *default
  host: <%= ENV.fetch('MYSQL_HOST', 'db') %>
  port: <%= ENV.fetch('MYSQL_PORT', 3306) %>
  database: app_test

production:
  <<: *default
  database: app_production
  username: app
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
