name: CI

env:
  MYSQL_HOST: 127.0.0.1
  MYSQL_ROOT_PASSWORD: 123456
  MYSQL_USERNAME: root
  MYSQL_PASSWORD: 123456
  MYSQL_ALLOW_EMPTY_PASSWORD: yes
  MYSQL_DATABASE: app_test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_USERNAME: root
          MYSQL_PASSWORD: 123456
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: app_test
        ports:
          - "3306:3306"
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: '3.0.5'

      - name: Install dependencies
        run: bundle install

      - name: Setup MySQL
        run: |
          sudo apt-get install -yqq mysql-client libmysqlclient-dev

      - name: Setup database
        run: |
          RAILS_ENV=test bundle exec rails db:create db:migrate

      - name: Run Tests
        run: RAILS_ENV=test bundle exec rspec

